server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_microservice?createDatabaseIfNotExist=true
    username: root
    password: seaface
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect